[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_DEEPSEEK_API_KEY = "your_deepseek_api_key_here"
  VITE_GEMINI_API_KEY = "your_gemini_api_key_here"
  VITE_DEFAULT_AI_PROVIDER = "DEEPSEEK"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"