name = "xuanzemate"
compatibility_date = "2025-08-25"
compatibility_flags = ["nodejs_compat"]

[env.production]
account_id = "your_account_id_here"
zone_id = "your_zone_id_here"

[env.production.vars]
VITE_DEEPSEEK_API_KEY = "your_deepseek_api_key_here"
VITE_GEMINI_API_KEY = "your_gemini_api_key_here"
VITE_DEFAULT_AI_PROVIDER = "DEEPSEEK"
